SSPAIR 1-2.A.0
HSSTRIPLET 1,1-2;2,1-2
0   V   LX   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   G   LG   R
0   V   LB   R
0   V   LB   R
0   V   EB   R
0   V   EB   R
0   V   EB   R
0   G   LG   R
0   G   LG   R
0   V   EB   R
0   V   EB   R
0   V   EB   R
0   V   LB   R
0   V   LB   R
0   G   LG   R
0   V   LB   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   HA   R
0   V   LX   R
