# This file is for limiting the number of glycines in a pose using the
# `aa_composition` mover, restricting the number of glycines to zero or <<one>> by
# imposing a 100-point penalty to anything with one glycine, with an even
# higher penalty for more glycines.
PENALTY_DEFINITION
TYPE GLY
ABSOLUTE 0
PENALTIES 0 0 100
DELTA_START 0
DELTA_END 2
BEFORE_FUNCTION CONSTANT
AFTER_FUNCTION CONSTANT
END_PENALTY_DEFINITION
