# This file is for limiting the number of alanines in a pose using the
# `aa_composition` mover, restricting the number of alanines to zero by
# imposing a 100-point penalty to anything with one alanine, with an even
# higher penalty for more alanines.
PENALTY_DEFINITION
TYPE ALA
ABSOLUTE 0
PENALTIES 0 100
DELTA_START 0
DELTA_END 1
BEFORE_FUNCTION CONSTANT
AFTER_FUNCTION CONSTANT
END_PENALTY_DEFINITION
